name: CI Pipeline

on:
  push:
    branches:
      - contact
  pull_request:
    branches:
      - contact



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show project files
        run: ls -la

      - name: CI finished
        run: echo "CI pipeline executed successfully ✅"